apiVersion: v1
kind: Namespace
metadata:
  name: ftp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp
  namespace: ftp
  labels:
    app: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: kauden/pure-ftpd-mysql
        ports:
        - containerPort: 21
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: "/etc/ssl/private/pure-ftpd.pem"
          subPath: tls.crt
          readOnly: true
        - name: data
          mountPath: "/ftpdata"
    volumes:
    - name: tls
      secret:
        secretName: ftp-tls
    - name: data
      nfs:
        server: 10.110.110.221
        path: /
